name: pytorch
channels:
  - pytorch
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - conda-forge::numpy
  - conda-forge::jupyterlab
  - conda-forge::notebook
  - conda-forge::pandas
  - conda-forge::matplotlib
  - pytorch::pytorch